services:
  _defaults:
    public: true
    autowire: true
    bind:
      BnplPartners\Factoring004\Transport\TransportInterface: '@BnplPartners\Factoring004\Transport\PsrTransport'

  BnplPartnersFactoring004Prestashop\Controller\FileHandlerController:
    class: BnplPartners\Factoring004Prestashop\Controller\FileHandlerController
    arguments:
      - '@doctrine.cache.provider'
  PrestaShopBundle\Controller\Admin\Sell\Order\OrderController:
    class: BnplPartners\Factoring004Prestashop\Controller\OrderController
    arguments:
      - [ '@BnplPartners\Factoring004Prestashop\Handler\DeliveryHandler', '@BnplPartners\Factoring004Prestashop\Handler\FullRefundHandler', '@BnplPartners\Factoring004Prestashop\Handler\PartialRefundHandler', '@BnplPartners\Factoring004Prestashop\Handler\CancelHandler' ]
  BnplPartners\Factoring004Prestashop\Controller\OtpController:
    class: BnplPartners\Factoring004Prestashop\Controller\OtpController
    arguments: ["@=service('factoring004_'~service('request_stack').getCurrentRequest().attributes.get('type')~'_otp_checker')"]
  BnplPartners\Factoring004Prestashop\Handler\DeliveryHandler:
    class: BnplPartners\Factoring004Prestashop\Handler\DeliveryHandler
  BnplPartners\Factoring004Prestashop\Handler\FullRefundHandler:
    class: BnplPartners\Factoring004Prestashop\Handler\FullRefundHandler
  BnplPartners\Factoring004Prestashop\Handler\PartialRefundHandler:
    class: BnplPartners\Factoring004Prestashop\Handler\PartialRefundHandler
  BnplPartners\Factoring004Prestashop\Handler\CancelHandler:
    class: BnplPartners\Factoring004Prestashop\Handler\CancelHandler
  BnplPartners\Factoring004\Transport\PsrTransport:
    class: BnplPartners\Factoring004\Transport\PsrTransport
    arguments:
      - '@Symfony\Component\HttpClient\Psr18Client'
      - '@Symfony\Component\HttpClient\Psr18Client'
      - '@Symfony\Component\HttpClient\Psr18Client'
      - '@Symfony\Component\HttpClient\Psr18Client'
    calls:
      - method: setLogger
        arguments:
          - '@logger'
  Symfony\Component\HttpClient\Psr18Client:
    class: Symfony\Component\HttpClient\Psr18Client
  'form.type.order.change_order_statuses':
    class: BnplPartners\Factoring004Prestashop\Form\ChangeOrdersStatusType
    arguments:
      - '@prestashop.core.form.choice_provider.order_state_by_id'
    tags:
      - { name: form.type }
  factoring004_delivery_otp_checker:
    class: BnplPartners\Factoring004Prestashop\Otp\DeliveryOtpChecker
  factoring004_refund_otp_checker:
    class: BnplPartners\Factoring004Prestashop\Otp\RefundOtpChecker
  factoring004_full_refund_otp_checker: '@factoring004_refund_otp_checker'
  factoring004_partial_refund_otp_checker: '@factoring004_refund_otp_checker'
